image:
  file: .gitpod/Dockerfile

ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - bazelbuild.vscode-bazel
    - ms-toolsai.jupyter
    - ms-python.python